### ISSUE TITLE
Haven't got answer after filling the form

### ISSUE THREAD

**Issue by RoyHirsch** [CAMMA-public/cholect45#1]
Hi, 
Thank you for this useful repo, I wish to access the data for academic research and filled out the form. However, I haven't got a replay from you, I'll be happy to get your assistance with accessing the data.

**Comment by nwoyecid** [comment]
Hello, 

To check from my end, provide your registered email address for the dataset request.
Before then, please, check your spam folder and filter.

Thanks

**Comment by RoyHirsch** [comment]
Thank you for returning my request, I've registered with:
***@***.***
My name is Roy Hirsch and I'm a student at Tel Aviv University, Israel,
interested in accessing the dataset for academic research.

Thank you and have a great weekend.
Roy

**Comment by RoyHirsch** [comment]
Hi, I've received your email but unfortunately the password is incorrect. I would appreciate your help with suppling the correct password
