### ISSUE TITLE
I haven't received any email after filling the form 

### ISSUE THREAD

**Issue by aperezr20** [CAMMA-public/cholect45#2]
Hi! 

I filled the form and sent an email to camma.dataset@gmail.com to request CholecT45 data for our internal academic research at CINFONIA, Universidad de los Andes (Bogota). We haven't received an answer 

We would appreciate an answer to access data 

Thank you!

**Comment by aperezr20** [comment]
The email we used to fill the form was a.perezr20@uniandes.edu.co

**Comment by nwoyecid** [comment]
The form is back online!
